###
POST http://localhost:5000/api/v1/register
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
POST http://localhost:5000/api/v1/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
GET http://localhost:5000/api/v1/getMe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOiIyOTM4ZjRiMS05NTc3LTQ3MzEtODkwNy0xNDE5NTk4NWVkYTYiLCJpYXQiOjE3NDgwMTAxMzYsImV4cCI6MTc0ODA5NjUzNn0.xyqS5PBvdonW9KjTq2iRSJdye9IcFpIha9CGYfjk50g

###
POST http://localhost:5000/api/v1/registerEvent/45435343657
Content-Type: application/json

{
  "email": "user@email.com",
  "noHp": "08123456789",
  "transportasi": "Mobil",
  "keluargaUpdates": [
    {
      "nama": "Rina Putri",
      "umur": 35,
      "status_register": 1,
      "status_keluarga": "Istri"
    },
    {
      "nama": "Dino",
      "umur": 5,
      "status_register": 1,
      "status_keluarga": "Anak"
    },
    {
      "nama": "Lala",
      "umur": 16,
      "status_register": 1,
      "status_keluarga": "Anak"
    }
  ]
}

###
GET http://localhost:5000/api/v1/keluarga/2240605

###
GET http://localhost:5000/api/v1/pieChart

###
GET http://localhost:5000/api/v1/karyawan

###
GET http://localhost:5000/api/v1/allKeluarga

###
DELETE http://localhost:5000/api/v1/karyawan/345345


###
GET http://localhost:5000/api/v1/getUserGacha/lucky_dip

###
POST http://localhost:5000/api/v1/addWinnersGacha/lucky_dip
Content-Type: application/json

{   
  "listWinners": [
    {
      "idRegistration": "8b562c9b-a17b-4e45-8a01-e76ccbea9a9d",
      "idPrize": "b3a0327d-2e4f-11f0-931d-00a554bb4e40"
    },
    {
      "idRegistration": "9246f0bf-fb0a-4439-a12a-37c621d0e163",
      "idPrize": "b3a0327d-2e4f-11f0-931d-00a554bb4e40"
    }
  ]
}

###
GET http://localhost:5000/api/v1/prizes